"""add complete field to Todo

Revision ID: 7971e03e1784
Revises: b42f1f290c08
Create Date: 2018-12-24 16:49:13.482410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7971e03e1784'
down_revision = 'b42f1f290c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.Boolean(), default = False, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('complete')

    # ### end Alembic commands ###
